#!/usr/bin/env bash

# Expand the arguments into an array of strings. This is required because the GitHub action
# provides all arguments concatenated as a single string.
ARGS=("$@")

# In order to avoid facing GitHub API rate limits, we use Github Action's default token which is set as an
# environment variable called GITHUB_TOKEN.
# This token is automatically generated by GitHub and is scoped to the repository that is currently running the action.
# You can override the value with a custom personal access token (PAT) if it needs to access private repositories.

# Using -n instead of ! -z: https://github.com/koalaman/shellcheck/wiki/SC2236
if [[ -n "${GITHUB_TOKEN}" ]]; then
  git config --global --add url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
fi

/bin/gosec "${ARGS[*]}"