#!/usr/bin/env bash
# This file was inspired by gosec project

# Binary name based on the value specified in Dockerfile
BIN_NAME=olaudit

# Expand the arguments into an array of strings. This is required because the GitHub action
# provides all arguments concatenated as a single string.
ARGS=("$@")

# In order to avoid facing GitHub API rate limits, we use Github Action's default token which is set as an
# environment variable called GITHUB_TOKEN.
# This token is automatically generated by GitHub and is scoped to the repository that is currently running the action.
# You can override the value with a custom personal access token (PAT) if it needs to access private repositories.

# Using -n instead of ! -z: https://github.com/koalaman/shellcheck/wiki/SC2236
if [[ -n "${GITHUB_TOKEN}" ]]; then
    # Check if we are inside a Git repository
    if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
      git config --local --add url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
    else
      echo "Warning: Not inside a Git repository. Skipping git configuration."
    fi
else
    echo "Warning: GITHUB_TOKEN is not set. Skipping git configuration."
fi

/bin/${BIN_NAME} "${ARGS[*]}"