name: run-security-checks

on:
  schedule:
    # Once a week at midnight on Sunday
    - cron: '0 0 * * 0'

jobs:
  run-go-sec-scanner:
    name: Run GoSec Security Scanner
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GO111MODULE: on
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Download modules
        run: |
          go mod download
      - name: Run GoSec Security Scanner
        run: |
          docker run --rm -it -e GO111MODULE=on -v $(pwd):/code securego/gosec:latest -no-fail -exclude-dir=test/fixtures /code/... >> gosec-report.txt
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: gosec-report
          path: gosec-report.txt
          if-no-files-found: error
          retention-days: 30
