name: security-checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
  schedule:
    # Once a week at midnight on Sunday
    - cron: '0 0 * * 0'

jobs:
  run-go-sec-scanner:
    name: Run GoSec Security Scanner
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GO111MODULE: on
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Download modules
        run: |
          go mod download
      - name: Run GoSec Security Scanner
        # TODO: Later remove -no-fail to fail and trigger on PR
        run: |
          docker run --rm -e GO111MODULE=on -v $(pwd):/code securego/gosec:latest -no-fail -exclude-dir=test/fixtures /code/... >> gosec-report.txt
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: gosec-report
          path: gosec-report.txt
          if-no-files-found: error
          retention-days: 7

  snyk-security-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
