name: self-assign-author

on:
  pull_request:
    branches:
      - master
    types: [opened]

jobs:
  self-assign-author:
    name: Self assign author
    permissions:
      issues: read
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_PR_COMMENTER_TOKEN }}
      - name: Self assign author
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.addAssignees({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            assignees: [context.payload.pull_request.user.login]
            })
